# Generated by Django 3.1.1 on 2020-09-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20200918_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='content',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
