# Generated by Django 3.1.1 on 2020-09-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20200918_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default=34, max_length=50, upload_to='media'),
            preserve_default=False,
        ),
    ]
