# Generated by Django 3.1.1 on 2020-09-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_auto_20200918_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
