# Generated by Django 3.1.1 on 2020-09-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_auto_20200918_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
